[google_service_account]
type = "service_account"
project_id = "my-project-52318-465707"
private_key_id = "65654ab976f668b664f21cf4c8392f823c6ef466"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC9ppQH11wzeRLI
lQXcuGxR+84wSKoW6HX6RNdhRXzgkdn9nyuUXOcAXAa8au7c2yONoeTjzaPGLuIf
88gRPvPyJwsj0Ug1NrQk5f+9HUh+q9Ai5eKOHwGJJC/a52cK0oEl+iSFaSXty1IS
ZqTspiLaIB65taMG9QJsK0b9+Jir42IrdQvNlVtlhG3ksVDNagzGYT65qDp1O6Jk
d+2APAYVeBpZL6Gxs9ygRy1w00rziCnKZ4/egRCDbR/Hojljf3UwFEYDNymrNLon
S+zjg3CLjqkAbE8V74j4jCgL9DSrCQJZ9jjyzCBQwrXxk/iSsOReTnY+ySgkhPQG
CN+oA/3lAgMBAAECggEABpFuU5cxztaOCR/EseuoC5NmF4qRRywcswdYd18Xkcrp
DT1Ki/H+BPCYr7Jo810srgsLCSr4VaJ8Ulpl42nfTYp+6EWCqrCO43hBbpIgfAu7
1QvcjxQRiYwVAMar/3rPcION1xohuG8mysoQ+eErqq/2qZfZ9GqVkcBShRk0sGPL
sISzGVTQOXcAhX+HQfcmA2lJMFQgmnG5Ti0ZC5pQJsL+FXRYjck1SsEwP/5i4TO8
gRWEg4MYSXHCVDczf+XIKrjIH0IAr5GZGa7s0GmKfl4WA83v7N2vIavcprrHunWb
wxurGqgrFsmaXQC4FWzqqVwYC7eFQhyUETtUM6rrQQKBgQD033ebzS/bwxNos4NP
tkoEXuzralGA1pL/9KOYepiCtOd90d+17gx+7PvJJD7fvOIgb1lFSpUkpkPuAmIq
cLJc/FrSTh5SO/pPMzLVux/Mst3+lNd9OzvRQsyXT0DHatliRdo2kb1Pi9ymWG+d
1Km9bu/zpyheo1FoAWlbRpvw4wKBgQDGRLpCE5zhR2UQ7iUW1dKQn3ofcB/3I2xm
oy8Jyv7/QpAQnn+U5sY2lSyAyDjU9bWBdu2xMmL8PPZeNmH95/UtBwRpAQnlLb77
mTgRTZHYk+t3a2S0iP1itQYinrsTt5eXnnxfP7CVl4LvJKdC2MqO5VOGGBBOegiR
788dHS/4lwKBgQDi99J8heZLMvhlfqZClzrp7DZ7ShN7cOfV+KI+Lbv4wscitwo9
LgVFDFGgsUjZxtBtseezsxqkWrvx+yGUJtscFwfzkFbIcDFlgZYnxwcFi/D6DGnj
+KhMITdTNDFd5WrSjN5i4Bjxhzigsq3aRAiEvjQIyjI/7e8BkPVflgXqcwKBgEuc
cC+8zQo4sPlI6IoR1zBiMS+GEhqsvq1RtCGW8bIlD03XNC5z58lvED64nLvSTHro
APOflJI/KXF6adpruFuInozw4XYuAPRwVSp8G4+tsZGkOg6DY6ZeBM31HMEDNeOT
hDjK0CvsUPmkT8k1ZeIi4Lx1ttpGvbfx7VlcBSxXAoGBAMAzDcNA5SXLwFVoBwYa
S0o+pc9WGhaQGeTwQDWCDAs0mGK+o8U3SKml++/j98gUlYuQkGHlt8R8YEXdlFyE
MWFUX1rPu1uu+ZxFSmS5bJLTQSDnXzaUFj0EnJ1/bQcCqaRVf41miEBO9Q8Qq1ex
7XT4cpdF4vaPRdPBjWfxdecy
-----END PRIVATE KEY-----"""
client_email = "cadet-dashboard-bot@my-project-52318-465707.iam.gserviceaccount.com"
client_id = "110130940355208169509"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cadet-dashboard-bot%40my-project-52318-465707.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
password = "C00L$kill$"
